## Load the data for analysis

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import nltk, os
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

## Reload the data for analysis

In [2]:
def load_data(file_path):
    """
    Load the dataset from the specified file path.
    """
    return pd.read_csv(file_path)


fake_data = load_data('../Data_collect/Dataset/Fake_data.csv')
true_data = load_data('../Data_collect/Dataset/True_data.csv')

In [3]:
fake_data.head()

                                           text_fake  label
0   Donald Trump Sends Out Embarrassing New Year’...      0
1   Drunk Bragging Trump Staffer Started Russian ...      0
2   Sheriff David Clarke Becomes An Internet Joke...      0
3   Trump Is So Obsessed He Even Has Obama’s Name...      0
4   Pope Francis Just Called Out Donald Trump Dur...      0

In [4]:
true_data.head()

                                                text  label text_news
0  China's Honor launches new challenge to Samsun...      1   Unknown
1  European heat wave closes Eiffel Tower’s top f...      1   Unknown
2  US pauses some munitions shipments to Ukraine,...      1   Unknown
3  Democrats, the last holdout bears, could be th...      1   Unknown
4  CBS owner Paramount settles Trump lawsuit over...      1   Unknown

### Concatenate the fake and true datasets

In [5]:
true_data["text_true"] = true_data['text'] + "" + true_data['text_news']

true_data = true_data.drop(columns=['text', 'text_news'])

true_data.head()

   label                                          text_true
0      1  China's Honor launches new challenge to Samsun...
1      1  European heat wave closes Eiffel Tower’s top f...
2      1  US pauses some munitions shipments to Ukraine,...
3      1  Democrats, the last holdout bears, could be th...
4      1  CBS owner Paramount settles Trump lawsuit over...

In [6]:
true_data.shape, fake_data.shape

((22142, 2), (23481, 2))

In [8]:
true_new = '../Data_collect/Dataset/True_news.csv'
true_news = load_data(true_new)
true_news.head()

,title,description,author,content,published_at,source,category
0,China's Honor launches new challenge to Samsun...,"Honor launched the Magic V5 on Wednesday, it's...",Arjun Kharpal,Honor on Wednesday touted the slimness and bat...,2025-07-02 12:01:24,CNBC,general
1,European heat wave closes Eiffel Tower’s top f...,The heat wave that has blanketed much of Europ...,"Andrew Jeong, Ben Noll","In Paris, blistering heat led the Eiffel Tower...",2025-07-02 11:30:55,The Washington Post,general
2,"US pauses some munitions shipments to Ukraine,...",The Trump administration is pausing some weapo...,"Kristen Holmes, Lex Harvey",The Trump administration is pausing some weapo...,2025-07-02 11:19:00,CNN,general
3,"Democrats, the last holdout bears, could be th...",Ned Davis strategists say politics are keeping...,Barbara Kollmeyer,"The S&amp;P 500, basking in the glow of record...",2025-07-02 10:56:00,MarketWatch,general
4,CBS owner Paramount settles Trump lawsuit over...,The money will go to Trump’s future presidenti...,Jeremy Barr,"Paramount, the parent company of CBS News, has...",2025-07-02 10:54:13,The Washington Post,general

In [9]:
true_news.shape, true_news.isnull().sum()

((912, 7),
 title             0
 description      12
 author          203
 content          24
 published_at      0
 source            0
 category          0
 dtype: int64)

In [12]:
true_news['text'] = true_news['title']+ "" + true_news['description']+ "" + true_news['content']
true_news['label']=1
true_news.head()

,title,description,author,content,published_at,source,category,text,label
0,China's Honor launches new challenge to Samsun...,"Honor launched the Magic V5 on Wednesday, it's...",Arjun Kharpal,Honor on Wednesday touted the slimness and bat...,2025-07-02 12:01:24,CNBC,general,China's Honor launches new challenge to Samsun...,1
1,European heat wave closes Eiffel Tower’s top f...,The heat wave that has blanketed much of Europ...,"Andrew Jeong, Ben Noll","In Paris, blistering heat led the Eiffel Tower...",2025-07-02 11:30:55,The Washington Post,general,European heat wave closes Eiffel Tower’s top f...,1
2,"US pauses some munitions shipments to Ukraine,...",The Trump administration is pausing some weapo...,"Kristen Holmes, Lex Harvey",The Trump administration is pausing some weapo...,2025-07-02 11:19:00,CNN,general,"US pauses some munitions shipments to Ukraine,...",1
3,"Democrats, the last holdout bears, could be th...",Ned Davis strategists say politics are keeping...,Barbara Kollmeyer,"The S&amp;P 500, basking in the glow of record...",2025-07-02 10:56:00,MarketWatch,general,"Democrats, the last holdout bears, could be th...",1
4,CBS owner Paramount settles Trump lawsuit over...,The money will go to Trump’s future presidenti...,Jeremy Barr,"Paramount, the parent company of CBS News, has...",2025-07-02 10:54:13,The Washington Post,general,CBS owner Paramount settles Trump lawsuit over...,1

In [13]:
true = true_news[['text', "label"]]
true.isna().sum()

text     29
label     0
dtype: int64

In [14]:
true

                                                  text  label
0    China's Honor launches new challenge to Samsun...      1
1    European heat wave closes Eiffel Tower’s top f...      1
2    US pauses some munitions shipments to Ukraine,...      1
3    Democrats, the last holdout bears, could be th...      1
4    CBS owner Paramount settles Trump lawsuit over...      1
..                                                 ...    ...
907  How X CEO Linda Yaccarino went from Elon Musk'...      1
908  Deion Sanders: I wish college football had a s...      1
909  How X CEO Linda Yaccarino went from Elon Musk'...      1
910  Deion Sanders: I wish college football had a s...      1
911  How X CEO Linda Yaccarino went from Elon Musk'...      1

[912 rows x 2 columns]

In [15]:
true.to_csv('test.csv', index=False)